// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQ2Z4NHySgIDwkqgBK9hAc1xnWsFXr7U',
    appId: '1:131485264548:web:2c61e15ac80faff1381431',
    messagingSenderId: '131485264548',
    projectId: 'aprende-app-cm',
    authDomain: 'aprende-app-cm.firebaseapp.com',
    storageBucket: 'aprende-app-cm.firebasestorage.app',
    measurementId: 'G-4X755L7PP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvggbh6ietZWaG2CeXPkQtIpfNjWhym_I',
    appId: '1:131485264548:android:5703858cbb96882a381431',
    messagingSenderId: '131485264548',
    projectId: 'aprende-app-cm',
    storageBucket: 'aprende-app-cm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2yRAcSuMD9jo1ND8Jz9eT-wP8kvrDvJA',
    appId: '1:131485264548:ios:7c78aa6a42aa9c96381431',
    messagingSenderId: '131485264548',
    projectId: 'aprende-app-cm',
    storageBucket: 'aprende-app-cm.firebasestorage.app',
    iosBundleId: 'com.example.aprendeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2yRAcSuMD9jo1ND8Jz9eT-wP8kvrDvJA',
    appId: '1:131485264548:ios:7c78aa6a42aa9c96381431',
    messagingSenderId: '131485264548',
    projectId: 'aprende-app-cm',
    storageBucket: 'aprende-app-cm.firebasestorage.app',
    iosBundleId: 'com.example.aprendeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQ2Z4NHySgIDwkqgBK9hAc1xnWsFXr7U',
    appId: '1:131485264548:web:4a70a1621607bae8381431',
    messagingSenderId: '131485264548',
    projectId: 'aprende-app-cm',
    authDomain: 'aprende-app-cm.firebaseapp.com',
    storageBucket: 'aprende-app-cm.firebasestorage.app',
    measurementId: 'G-F4ZXJXV7TE',
  );
}
